[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llava-3d"
version = "1.0.0"
description = "A Simple yet Effective Pathway to Empowering LMMs with 3D-awareness."
readme = "README.md"
requires-python = "==3.11.11"
authors = [
  { name = "Your Name", email = "you@example.com" }
]
license = { text = "Apache-2.0" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License"
]
dependencies = [
  "transformers==4.37.2",
  "tokenizers",
  "sentencepiece",
  "shortuuid",
  "accelerate",
  "peft",
  "bitsandbytes",
  "pydantic",
  "numpy",
  "markdown2[all]",
  "scikit-learn",
  "gradio",
  "gradio_client",
  "requests",
  "httpx",
  "uvicorn",
  "fastapi",
  "einops",
  "einops-exts",
  "timm",
  "opencv-python",
  "protobuf",
  "torch==2.5.1",
  "torchvision==0.20.1",
  "torchaudio==2.5.1",
  "flash-attn",  
  "torch-scatter",
  "torch-sparse",
  "torch-cluster",
  "torch-spline-conv",
  "torch-geometric",
  "mmengine-lite"
]

[project.optional-dependencies]
train = [
  "deepspeed",
  "ninja",
  "wandb"
]
build = [
  "build",
  "twine"
]

[tool.setuptools.packages.find]
exclude = ["assets*", "benchmark*", "docs", "dist*", "playground*", "scripts*", "tests*"]
